{
 "title": "Customer meter_id = %s dashboard",
 "time": { "from": "now-7d", "to": "now+1d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Energy consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "consumption",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_meter",
     "query": "SELECT \"value\" FROM \"smart_meter\" WHERE (\"is_data_real\" = 'True') AND meter_id = %s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "is_data_real", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "expected consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"predicted_test\" WHERE time >= now() - 1h AND time <= now() + 2d AND meter_id = %s  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"smart_meter\" WHERE $timeFilter AND \"is_data_real\" = 'True' AND meter_id = %s GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "expected consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"predicted_test\" WHERE $timeFilter AND meter_id = %s AND time > now() GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"smart_meter\" WHERE is_data_real = 'True' AND meter_id = %s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Price for total consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") * 0.00233 FROM \"smart_meter\" WHERE is_data_real = 'True' AND meter_id = %s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}